version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  build-tags:
    - ignore_ocr

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - revive
    - gocyclo
  disable:
    # Disabled temporarily - many false positives in test files and output file operations
    - gosec
    # Disabled - contains WIP v6 parser functions that will be used
    - unused
    # Disabled - repeated test strings are acceptable in test files
    - goconst

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: internal/ocr/
      linters:
        - typecheck
    - text: "could not import github.com/otiai10/gosseract"
      linters:
        - typecheck
    # Unused code in rmrender is work-in-progress for v6 format parsing
    - path: internal/rmrender/
      linters:
        - unused
    # Test files: allow repeated strings and file operations
    - path: _test\.go
      linters:
        - goconst
        - gosec
    # Directories with 0755 permissions are appropriate for user-facing output
    - text: "G301.*MkdirAll.*0755"
      linters:
        - gosec
    # Output files with 0644 permissions are appropriate
    - text: "G306.*WriteFile.*0644"
      linters:
        - gosec
    - text: "G302.*OpenFile.*0644"
      linters:
        - gosec
    # State files with 0644 are appropriate for non-sensitive state data
    - path: internal/state/state\.go
      text: "G306.*WriteFile"
      linters:
        - gosec
    # ZIP extraction with validation is acceptable
    - path: internal/converter/converter\.go
      text: "(G305|G304|G110)"
      linters:
        - gosec
    # File reading in rmrender is from trusted local files
    - path: internal/rmrender/parser\.go
      text: "G304"
      linters:
        - gosec
