# GoReleaser configuration for macOS menu bar app builds (CI)
# Used by CI to build the legible-menubar application with CGO on macOS runners
# Requires macOS runner with CGO_ENABLED=1 for systray support

version: 2

project_name: legible

before:
  hooks:
    - go mod tidy

builds:
  # CLI daemon binary (needed by menu bar app)
  - id: legible
    main: ./cmd/legible
    binary: legible

    # macOS only - daemon for menu bar app
    goos:
      - darwin

    goarch:
      - amd64
      - arm64

    # Inject version information
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}

    env:
      - CGO_ENABLED=0  # Daemon doesn't need CGO

    flags:
      - -trimpath

    hooks:
      post:
        - cmd: echo "Built {{.Path}} for {{.Os}}/{{.Arch}}"

  # Menu bar application
  - id: legible-menubar
    main: ./cmd/legible-menubar
    binary: legible-menubar

    # macOS only - menu bar application
    goos:
      - darwin

    goarch:
      - amd64
      - arm64

    # Inject version information
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

    env:
      - CGO_ENABLED=1  # systray requires CGO on macOS

    flags:
      - -trimpath

    hooks:
      post:
        - cmd: bash -c 'if [ "{{.Os}}" = "darwin" ]; then OUTPUT_DIR=$(dirname $(dirname "{{.Path}}")); ./scripts/package-macos-app.sh "{{.Path}}" "$OUTPUT_DIR" "{{.Version}}"; fi'

archives:
  - id: macos-menubar
    builds:
      - legible-menubar
      - legible
    name_template: >-
      {{ .ProjectName }}-menubar_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

    format: zip

    # Include the .app bundle and daemon binary
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - FAQ.md
      - src: "dist/legible_*/Legible.app"
        dst: "."
        strip_parent: true

# DMG installer for macOS (GoReleaser Pro only)
# Note: This section requires GoReleaser Pro and will not work with the open-source version
# The CI/CD pipeline uses GoReleaser Pro for releases
dmg:
  - id: legible-menubar-dmg
    # Use the .app bundle created by the post-hook
    use: appbundle

    # Only create DMG for darwin builds
    ids:
      - legible-menubar

    # DMG filename
    name: "legible-menubar_{{.Version}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: platinummonkey
    name: legible

  # Keep as draft - will be published in final stage
  draft: true

  # Mark as prerelease for v0.x versions
  prerelease: auto

  # Don't fail if release already exists (it will be created by stage 1)
  mode: append

# Homebrew tap - automatically updates platinummonkey/homebrew-tap
# Using homebrew_casks (not brews) since we distribute pre-compiled binaries
homebrew_casks:
  # Menu bar application cask (using DMG)
  - name: legible-menubar
    repository:
      owner: platinummonkey
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    directory: Casks

    # Use DMG artifacts
    ids:
      - legible-menubar-dmg

    homepage: "https://github.com/platinummonkey/legible"
    description: "macOS menu bar application for syncing documents from reMarkable tablet"

    caveats: |
      Legible menu bar app has been installed to /Applications/Legible.app

      The 'legible' daemon is also required. Install it with:
        brew install platinummonkey/tap/legible

      First-time setup:
        1. Authenticate: legible auth
        2. Launch Legible.app from /Applications/
        3. The menu bar icon will appear and manage syncing automatically

      Optional: Install Ollama for OCR text layer generation (searchable PDFs):
        brew install ollama
        ollama pull llava

      Documentation: https://github.com/platinummonkey/legible/blob/main/docs/menubar-app.md

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
